name: first-interaction

on:
  issues:
    types: [opened]
  pull_request:
    branches: [master]
    types: [opened]

jobs:
  check_for_first_interaction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/first-interaction@main
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Hello! Thank you for filing an issue.

            We are thrilled to see you take your first step in contributing to our project with your issue.
            
            This community thrives on collaboration, and we greatly appreciate your interest and efforts in making our project even better.
          pr-message: |
            Hello! Thank you for your contribution.
            
            Read the Guidelines: Familiarize yourself with our contributing guidelines.
            
            These guidelines outline the code of conduct, coding standards, and the overall contribution process.
            
            You can find these guidelines in the repository's .github/CONTRIBUTING.md file.
            
            We are thrilled to see you take your first step in contributing to our project with your pull request. 
            
            This community thrives on collaboration, and we greatly appreciate your interest and efforts in making our project even better.
            
            If you are fixing a bug, please reference the issue number in the description.

            If you are implementing a feature request, please check with the maintainers that the feature will be accepted first.
            
            Ensure that your changes are clear, concise, and address a specific problem or feature.
            
            Add detailed descriptions to help our reviewers understand your intent better.
            
             If applicable, make sure your code passes any relevant tests.
